// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwtsjralwchuxucbqzts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3dHNqcmFsd2NodXh1Y2JxenRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTMwOTIsImV4cCI6MjA2Mjc4OTA5Mn0.Fn6Vw-R9E6WOtrLaAv1Pd2iTc7Vc1I9FB4ZyLs8PeSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);